services:
  drupal:
    image: centurylink/drupal:7.28
    command: exec supervisord -n
    ports:
    - 80:80:443
    health:
      type: normal
      endpoint: "/"
      protocol: http
      timeout: 120s
      accept:
      - '200'
      - 300-399
    restart_on_deploy: false      
databases:
- mysql