services:
  gitlab:
    image: sameersbn/gitlab:7.7.2
    ports:
    - 80:80:443
    health:
      type: normal
      endpoint: "/"
      protocol: http
      timeout: 600s
      accept:
      - '200'
      - 300-399
    restart_on_deploy: false  
databases:
- mysql
- redis